import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#1000a9',
        'surface-container': '#f0f4f8',
        'tertiary-fixed': '#e1e0ff',
        'on-secondary-fixed': '#002113',
        'surface-container-lowest': '#ffffff',
        'inverse-primary': '#006970',
        'outline-variant': '#d1d9da',
        'on-tertiary-container': '#494bd7',
        'inverse-surface': '#2e3037',
        'tertiary-container': '#d7d6ff',
        'on-tertiary-fixed-variant': '#2f2ebe',
        'secondary-container': '#00a572',
        'error-container': '#ffdad6',
        'surface-bright': '#ffffff',
        'surface-dim': '#f1f3f4',
        'on-primary-fixed-variant': '#004f54',
        'surface-container-high': '#e2e8f0',
        'inverse-on-surface': '#ffffff',
        primary: '#006970',
        secondary: '#00a572',
        'on-background': '#1a1c1e',
        'surface-container-highest': '#cbd5e1',
        'surface-container-low': '#f8fafc',
        'tertiary-fixed-dim': '#c0c1ff',
        outline: '#70787d',
        'on-secondary-fixed-variant': '#005236',
        surface: { DEFAULT: '#ffffff', muted: '#fafafa' },
        'on-surface-variant': '#44474e',
        'secondary-fixed-dim': '#4edea3',
        'surface-variant': '#dee3e5',
        'on-secondary-container': '#ffffff',
        'surface-tint': '#00dbe9',
        'on-surface': '#1a1c1e',
        tertiary: '#5e5ce6',
        'on-primary-fixed': '#002022',
        'on-error-container': '#410002',
        'on-primary': '#ffffff',
        'primary-container': '#7df4ff',
        'on-tertiary-fixed': '#07006c',
        background: '#f8fafc',
        'primary-fixed-dim': '#00dbe9',
        'on-secondary': '#ffffff',
        'on-primary-container': '#002022',
        'primary-fixed': '#7df4ff',
        'on-error': '#ffffff',
        'secondary-fixed': '#6ffbbe',
        error: '#ba1a1a',
        body: { DEFAULT: '#18181b', muted: '#71717a' },
      },
      borderRadius: {
        DEFAULT: '0.75rem',
        lg: '0.75rem',
        xl: '1rem',
        full: '9999px',
      },
      spacing: {
        md: '16px',
        'container-max': '1440px',
        gutter: '24px',
        base: '4px',
        xs: '4px',
        sm: '8px',
        lg: '24px',
        xl: '40px',
      },
      fontFamily: {
        'data-display': ['"JetBrains Mono"', 'monospace'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'label-caps': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'data-display': ['28px', { lineHeight: '32px', fontWeight: '500' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '600' }],
      },
      backgroundImage: {
        'brand-gradient': 'linear-gradient(90deg, #06b6d4 0%, #3b82f6 100%)',
      },
    },
  },
  plugins: [],
}
export default config
